version: '2'
services:
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: 'postgres:9.6'
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./config/docker-init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
volumes:
  db-data:
    external:
      name: loggingroads-onboarding-db-data