version: '2'
services:
  web:
    image: 'quay.io/loggingroads/website:latest'
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - /mnt/loggingroads/website/files:/app/public/system
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_USER=onboarding
      - DATABASE_PASSWORD=abc123
      - DATABASE_HOST=db
      - RAILS_ENV=production
      - POSTGRES_PASSWORD=abc123
  db:
    image: 'postgres:9.6'
    environment:
      - POSTGRES_PASSWORD=abc123
      - DATABASE_USER=onboarding
      - DATABASE_PASSWORD=abc123
    volumes:
      - /mnt/loggingroads/website/db-data:/var/lib/postgresql/data
      - /mnt/loggingroads/website/config/docker-init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"